### ISSUE TITLE
Usar regex para evitar problemas 

### ISSUE THREAD

**Issue by sbres** [AgnesMartinez/HuachiNet#1]
Yo creo que seria mas facil hacer el parcing de la quantidad del tip usando un regex.
Porque ahorita, el tip falla si alguien escribe algo despues del comando.
Ejemplo:
`!tip 35 Muchas gracias`

https://github.com/AgnesMartinez/HuachiNet/blob/a206cd1dade61e7814f2adcf7e5b82345b1cc574/empleado.py#L215
Probe rapidamente este regex y yo creo que podria servir.
`r"!tip\ *(\d+)"`

**Comment by AgnesMartinez** [comment]
Hice la prueba y definitivamente es mejor este método de parseo.

Muchas gracias por tu aportación :D
